import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/home';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Carrossel from '@/components/SecondCarroussel';


const Home = () => {

    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <S.Main>
                <S.ContainerFoto>
                    <img style={{width: '100%', height: '100%', zIndex: '0', objectFit: 'cover'}} src="/Ativo 173.png"/>
                    <S.SpanTitulo>Conheça a ÁgilMob.</S.SpanTitulo>
                    <S.DescricaoTitulo>Aqui vai o texto de apoio. Lorem ipsum dolor sit amet, consectetur adipicsing elit. Aliquam phatera laoreet orci quis scelerisque</S.DescricaoTitulo>
                </S.ContainerFoto>
                <div style={{backgroundColor: '#b5272d', height: '5rem', width: '100%', display: 'flex', gap: '1.5rem', justifyContent: 'center', alignItems: 'center'}}>
                    <img src='/Ativo 163.png'/>
                    <span style={{color: '#e6e1dd', fontSize: '1.6rem', fontWeight: '200'}}>Frete grátis para toda Fortaleza - CE!</span>
                </div>
                <S.ContainerValores>
                    <img src='/Ativo 164.png' style={{width: '15.2rem'}}/>
                    <S.BoxValores>
                        <S.Valores>
                            <S.TituloValores>MISSÃO</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Aqui vai breve texto introdutório. Lorem ipsum
dolor sit  amet, consectetur adipiscing elit.
Aliquam pharetra laoreet orci quis scelerisque.</p>
                        </S.Valores>
                        <S.Valores>
                            <S.TituloValores>VISÃO</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Aqui vai breve texto introdutório. Lorem ipsum
dolor sit  amet, consectetur adipiscing elit.
Aliquam pharetra laoreet orci quis scelerisque.</p>
                        </S.Valores>
                        <S.Valores>
                            <S.TituloValores>VALORES</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Aqui vai breve texto introdutório. Lorem ipsum
dolor sit  amet, consectetur adipiscing elit.
Aliquam pharetra laoreet orci quis scelerisque.</p>
                        </S.Valores>
                    </S.BoxValores>
                </S.ContainerValores>
                <S.ContainerGeral>
                    <S.ContainerProduto>
                        <img src='/Ativo 165.png' style={{width: '20rem', borderRadius: '1.1rem', height: '100%'}}/>
                        <S.SpanProdutos>MESAS</S.SpanProdutos>
                    </S.ContainerProduto>
                    <S.ContainerProduto>
                        <img src='/Ativo 175.png' style={{width: '20rem', borderRadius: '1.1rem', height: '100%'}}/>
                        <S.SpanProdutos>CADEIRAS</S.SpanProdutos>
                    </S.ContainerProduto>
                    <S.ContainerProduto>
                        <img src='/Ativo 176.png' style={{width: '20rem', borderRadius: '1.1rem', height: '100%'}}/>
                        <S.SpanProdutos>ARMÁRIOS</S.SpanProdutos>
                    </S.ContainerProduto>
                    <S.ContainerProduto>
                        <img src='/Ativo 177.png' style={{width: '20rem', borderRadius: '1.1rem', height: '100%'}}/>
                        <S.SpanProdutos>ROUPEIROS</S.SpanProdutos>
                    </S.ContainerProduto>
                </S.ContainerGeral>
                <div>
                </div>
            </S.Main>
            <Footer/>
        </>
    );
}

export default Home;

