import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router'; // Import the useRouter hook
import Head from 'next/head';
import * as S from '../styles/listaProdutos';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import axios from 'axios';

interface Product {
    id: number;
    image: string;
}

const productsData: Product[] = [
    {
        id: 1,
        image: 'cadeira 1.jpg',
    },
    {
        id: 2,
        image: 'cadeira 2.jpg',
    },
    {
        id: 3,
        image: 'cadeira 3.jpg',
    },
];

const ListaProdutos: React.FC = () => {
    const [products, setProducts] = useState<Product[]>([]);
    const router = useRouter(); 
    useEffect(() => {
        setProducts(productsData);
    }, []);

    const handleProductClick = (productId: number) => {
        router.push({
            pathname: '/Produto',
            query: { id: productId }
        });
    };

    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/Ativo 162.png"/>
            </Head>
            <NavBar />
            <S.Main>
                {products.map(product => (
                    <S.Produtos key={product.id} onClick={() => handleProductClick(product.id)}>
                        <img
                            style={{ width: '100%', height: '100%', borderRadius: '.3rem', objectFit: 'cover' }}
                            src={product.image} 
                        />
                    </S.Produtos>
                ))}
            </S.Main>
            <Footer />
        </>
    );
}

export default ListaProdutos;
