import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/produtos';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Carrossel from '@/components/SecondCarroussel';


const Produtos = () => {

    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <S.Main>
                <S.TipoProdutos>
                    <S.ContainerHover></S.ContainerHover>
                    <img style={{width: '100%', height: '100%', borderRadius: '.5rem'}} src='/Ativo 181.png'/>                
                    <S.SpanProdutos>MESAS</S.SpanProdutos>
                </S.TipoProdutos>
                <S.TipoProdutos>
                    <S.ContainerHover></S.ContainerHover>
                    <img style={{width: '100%', height: '100%', borderRadius: '.5rem'}} src='/Ativo 178.png'/>                
                    <S.SpanProdutos>CADEIRAS</S.SpanProdutos>
                </S.TipoProdutos>
                <S.TipoProdutos>
                    <S.ContainerHover></S.ContainerHover>
                    <img style={{width: '100%', height: '100%', borderRadius: '.5rem'}} src='/Ativo 179.png'/>                
                    <S.SpanProdutos>ARMÁRIOS</S.SpanProdutos>
                </S.TipoProdutos>
                <S.TipoProdutos>
                    <S.ContainerHover></S.ContainerHover>
                    <img style={{width: '100%', height: '100%', borderRadius: '.5rem'}} src='/Ativo 180.png'/>                
                    <S.SpanProdutos>ROUPEIROS</S.SpanProdutos>
                </S.TipoProdutos>
            </S.Main>
            <Footer/>
        </>
    );
}

export default Produtos;

