import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router'; // Import the useRouter hook
import Head from 'next/head';
import * as S from '../styles/Produto';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import axios from 'axios';

const Produto = () => {
    const [product, setProduct] = useState<any>(null);
    const [mainPhoto, setMainPhoto] = useState<string>('');
    const [selected, setSelected] = useState<string>('');
    const [showDetalhes, setShowDetalhes] = useState(false);

    const router = useRouter();

    useEffect(() => {
        const { id } = router.query;
        const sampleProductData = {
            id: id,
            name: 'Cadeira de escritório',
            description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt aut',
        };
        setProduct(sampleProductData);
        setMainPhoto(`cadeira ${id}.jpg`);
    }, [router.query]);

    if (!product) {
        return <div>Loading...</div>;
    }

    const handleSecondaryPhotoClick = (photoPath: string) => {
        setMainPhoto(photoPath);
        setSelected(photoPath);
    };

    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
                <link rel="icon" href="/Ativo 162.png" />
            </Head>
            <NavBar />
            <S.Main>
                <div style={{ backgroundColor: '#b5272d', height: '5rem', width: '100%', display: 'flex', gap: '1.5rem', justifyContent: 'center', alignItems: 'center' }}>
                    <img src='/Ativo 163.png' />
                    <span style={{ color: '#e6e1dd', fontSize: '1.6rem', fontWeight: '200' }}>Frete grátis para toda Fortaleza - CE!</span>
                </div>
                <S.BoxPrincipal>
                    <S.ContainerFotos>
                        <S.ColunaFotosSecundarias>
                            <S.FotosSecundarias src='cadeira 1.jpg' onClick={() => handleSecondaryPhotoClick('cadeira 1.jpg')} style={selected === 'cadeira 1.jpg' ? { outline: '1px solid #000' } : {}} />
                            <S.FotosSecundarias src='cadeira 2.jpg' onClick={() => handleSecondaryPhotoClick('cadeira 2.jpg')} style={selected === 'cadeira 2.jpg' ? { outline: '1px solid #000' } : {}} />
                            <S.FotosSecundarias src='cadeira 3.jpg' onClick={() => handleSecondaryPhotoClick('cadeira 3.jpg')} style={selected === 'cadeira 3.jpg' ? { outline: '1px solid #000' } : {}} />
                            <S.FotosSecundarias src='cadeira 4.jpg' onClick={() => handleSecondaryPhotoClick('cadeira 4.jpg')} style={selected === 'cadeira 4.jpg' ? { outline: '1px solid #000' } : {}} />
                            <S.FotosSecundarias src='cadeira 5.jpg' onClick={() => handleSecondaryPhotoClick('cadeira 5.jpg')} style={selected === 'cadeira 5.jpg' ? { outline: '1px solid #000' } : {}} />
                        </S.ColunaFotosSecundarias>
                        <S.ColunaFotoPrincipal>
                            <S.ImagemPrincipal src={mainPhoto} />
                        </S.ColunaFotoPrincipal>
                        <div></div>
                        <div style={{ display: 'flex', flexDirection: 'column', borderBottom: '1px solid #c6c6c6', width: '95%', alignItems: 'center'}}>
                            <div style={{display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center'}}>
                                <span style={{ color: '#666666', fontWeight: '500', fontSize: '1rem' }}>Descrição técnica:</span>
                                <button id='BtnAbrirDetalhes' onClick={() => setShowDetalhes(!showDetalhes)} style={{border: 'none', backgroundColor: 'transparent', color: '#666666', fontWeight: '500', fontSize: '1.8rem', margin: '0', cursor: 'pointer'}}>+</button>
                            </div>
                            <div id='detalhes' style={{display: showDetalhes ? 'flex' : 'none', flexDirection: 'column', textAlign: 'left', width: '100%'}}>
                                <ul style={{}}>
                                    <li style={{listStyle: 'none',color: '#666666', fontWeight: '500', fontSize: '1rem'}}>- Teste</li>
                                    <li style={{listStyle: 'none',color: '#666666', fontWeight: '500', fontSize: '1rem'}}>- Teste</li>
                                    <li style={{listStyle: 'none',color: '#666666', fontWeight: '500', fontSize: '1rem'}}>- Teste</li>
                                    <li style={{listStyle: 'none',color: '#666666', fontWeight: '500', fontSize: '1rem'}}>- Teste</li>
                                    <li style={{listStyle: 'none',color: '#666666', fontWeight: '500', fontSize: '1rem'}}>- Teste</li>
                                </ul>
                            </div>
                        </div>
                    </S.ContainerFotos>
                    <S.InfosPrincipais>
                        <h1 style={{ color: '#1e2952', fontWeight: '600', width: '100%', fontSize: '2.3rem' }}>{product.name.toUpperCase()}</h1>
                        <h2 style={{ fontWeight: '600', width: '100%', fontSize: '2rem' }}>R$ 999,99</h2>
                        <p style={{ color: '#666666', fontWeight: '500', width: '100%', fontSize: '.8rem' }}>{product.description}</p>
                        <div style={{ display: 'flex', justifyContent: 'center', placeSelf: 'center', gap: '1rem', alignItems: 'center', marginTop: '2rem' }}>
                            <span style={{ color: '#666666', fontWeight: '500', width: '100%', fontSize: '.8rem' }}>FALAR COM ATENDENTE</span>
                            <img src='/ChamarVendedor.svg' style={{ width: '1.5rem' }} />
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', alignItems: 'center' }}>
                            <S.Input1 placeholder='CEP'></S.Input1>
                            <S.Botao>CONSULTAR</S.Botao>
                        </div>
                    </S.InfosPrincipais>
                </S.BoxPrincipal>

            </S.Main>
            <Footer />
        </>
    );
}

export default Produto;
