import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/quemSomos';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Carrossel from '@/components/Carrossel';


const quemSomos = () => {

    const numeroWhatsApp = '+5585999556265'; 
    const mensagemWhatsApp = 'Olá, estou interessado em algum produto seu!'; 

    const linkWhatsApp = `https://api.whatsapp.com/send?phone=${numeroWhatsApp}&text=${encodeURIComponent(mensagemWhatsApp)}`;
    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/Ativo 162.png"/>
            </Head>
            <NavBar/>
            <S.Main>
                <div>
                    <S.ImagemPessoa1 src='/Ativo 167.png'/>
                    <S.ImgPrincipal src='/Ativo 166.png'/>
                    <S.ImagemPessoa2 src='/Ativo 168.png'/>
                </div>
                <div style={{width: '100%'}}>
                    <S.BoxDados>
                        <S.Dados>
                            <S.Infos>+ de 30</S.Infos>
                            <S.Infos2>Salas entregues</S.Infos2>
                        </S.Dados>
                        <S.Dados>
                            <S.Infos>+ de 30</S.Infos>
                            <S.Infos2>Móveis vendidos</S.Infos2>
                        </S.Dados>
                        <S.Dados>
                            <S.Infos>+ de 30</S.Infos>
                            <S.Infos2>Anos de experiência</S.Infos2>
                        </S.Dados>
                    </S.BoxDados>
                    <div style={{width:'100%', paddingTop: '3rem', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                        <p style={{width: '60%'}}> Durante nossos 10 anos de história, acompanhamos
muitas mudanças no mercado de móveis em Fortaleza, acompanhamos várias altas e
baixas do mercado imobiliário, a transformação do ambiente de trabalho para o home office
e até mesmo a vinda e ida do COVID-19. Pudemos acompanhar de perto a transformação
das preferencias do nosso cliente, que antes preferia ir ao local para comprar seus móveis e
hoje espera ser bem atendido nos meios online e ter seu pedido entregue de forma rápida.
Com isso nos adequamos aos novos gostos, aos novos objetivos e aos novos desejos de
nosso cliente, com o claro objetivo de entregar a facilidade desejada e a velocidade
esperada. Já são mais de 5 mil imóveis vendidos e 4 mil ambientes entregues.</p>
                    </div>
                </div>
                <S.ContainerValores>
                    <S.BoxValores>
                        <S.Valores>
                            <S.TituloValores>MISSÃO</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Ajudar a inspirar e evoluir pequenas e grandes empresas, tornando o ambiente de trabalhos
dos sonhos em realidade
</p>
                        </S.Valores>
                        <S.Valores>
                            <S.TituloValores>VISÃO</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Ser a empresa mais conhecida no ramo de móveis para escritório e a mais procurada no
momento de mobiliar o ambiente de trabalho
</p>
                        </S.Valores>
                        <S.Valores>
                            <S.TituloValores>VALORES</S.TituloValores>
                            <p style={{fontSize: '.9rem', width: '80%', alignSelf: 'center'}}>Confiança - Honramos nossa palavra através de atitudes éticas, honestas e transparentes;
Comunicação Clara, objetiva e eficaz;
Espírito de Equipe - Respeitamos o indivíduo e valorizamos o coletivo;
Excelência Operacional - Fazer com agilidade e bem feito tudo o que fazemos;
Foco no resultado - Com sentimento de dono, desenvolvimento contínuo, agilidade e
criatividade.
</p>
                        </S.Valores>
                    </S.BoxValores>
                </S.ContainerValores>
                <div style={{padding: '5%'}}>
                    <Carrossel/>
                </div>
            </S.Main>
            
            <S.BotaoWpp href={linkWhatsApp} target="_blank" rel="noopener noreferrer">
                <img src="/whats2.svg" alt="WhatsApp" />
            </S.BotaoWpp>
            <Footer/>
        </>
    );
}

export default quemSomos;

